In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [2]:
from sklearn.datasets import load_diabetes
data = load_diabetes()
X,Y = data.data , data.target

In [3]:
def gradeint(x,y,w):
    m = x.shape[0]
    return (x.T@x)@w - (x.T@y)

In [4]:
def gradient_descent(x,y,n,alpha):
    
    
    wi = np.zeros(x.shape[1],dtype=float)
    for i in range(n):
        wi -=  alpha*(gradeint(x,y,wi))
    
    return wi 

In [5]:
def predict_points(x,w,intercept):
    y_pred = np.zeros(x.shape[0],dtype=float)
    for i in range(len(x)):
        pred = np.dot(x[i],w)
        y_pred[i] = pred +intercept 
    return y_pred 
    

In [6]:
X_train,X_test = X[:340,], X[340:,]

In [7]:
X.shape

(442, 10)

In [8]:
X_train.shape

(340, 10)

In [9]:
Y_train,Y_test = Y[:340],Y[340:]

In [10]:
W = gradient_descent(X_train,Y_train,50,1e-10)

In [11]:
W

array([ 1.37604570e-06, -1.01514442e-07,  3.38328104e-06,  2.44356945e-06,
        1.42643487e-06,  1.23347082e-06, -2.39806911e-06,  2.92129216e-06,
        3.50872529e-06,  2.29525196e-06])

In [13]:
from sklearn.metrics import mean_squared_error,r2_score

In [14]:

x_scale = X_train- np.mean(X_train,axis=0)

In [15]:
W2 = gradient_descent(x_scale,Y_train,50,1e-1)

In [16]:
inter = np.mean(Y_train) - np.mean(X_train,axis=0)@W2

In [17]:
y_preds2 = predict_points(X_train,W2,inter)

In [19]:
print(mean_squared_error(Y_train,y_preds2))

2914.254019841914


In [20]:
r2_score(Y_train,y_preds2)

0.5042791355187524

In [21]:
y_preds_test = predict_points(X_test,W2,inter)

In [22]:
print(mean_squared_error(Y_test,y_preds_test))

2804.5236121194575


In [23]:
r2_score(Y_test,y_preds_test)

0.5398081491343298

In [24]:
Y_train

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [25]:
y_preds2

array([198.9709284 ,  70.04812459, 171.21988981, 164.28737241,
       126.16146203, 103.11812504,  77.96504234, 118.87563737,
       158.62994679, 213.28657364, 100.82242494, 104.0888693 ,
       113.77436118, 159.41276343,  99.97121413, 167.94174776,
       206.95531289, 177.57026904, 147.00967979, 121.00185644,
       121.3110634 ,  90.62800611, 118.07170062, 280.98846113,
       161.47537556, 143.42766659,  98.92562057, 179.27460994,
       127.64100174, 181.67215791, 158.05725478,  72.14194317,
       252.90686617, 108.83746496,  82.31135254,  85.55541249,
       202.07424461, 155.28737639, 237.35867686, 136.30824038,
       154.65698923,  79.77887531, 141.27261062,  85.76318338,
       213.70492344, 119.88037613, 136.91310462, 106.64114794,
        76.76173809, 183.85299613, 156.84124507, 163.3324701 ,
       132.93030092, 157.56237857, 140.40462154,  78.75288041,
       203.31198043,  81.2630068 ,  94.34501785, 133.02378816,
       115.51426563, 177.38683242,  68.57872314, 100.24