In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [215]:
rng = np.random.default_rng(seed=1)
X1 = np.concatenate((rng.binomial(size = 50,n = 1, p =0.7), rng.binomial(size = 50,n = 1, p =0.2))).reshape(-1, 1)
X2 = np.concatenate((rng.binomial(size = 50,n = 1, p =0.6), rng.binomial(size = 50,n = 1, p =0.1))).reshape(-1, 1)
X3 = np.concatenate((rng.binomial(size = 50,n = 1, p =0.6), rng.binomial(size = 50,n = 1, p =0.2))).reshape(-1, 1)
X4 = np.concatenate((rng.binomial(size = 50,n = 1, p =0.8), rng.binomial(size = 50,n = 1, p =0.1))).reshape(-1, 1)


X = np.column_stack((X1,X2,X3,X4))

y = np.concatenate((np.zeros(50, dtype= int), np.ones(50, dtype = int))).reshape(-1, 1)
permute = rng.permuted(range(100)) 

X = X[permute]
y = y[permute]

In [216]:
X.shape

(100, 4)

In [217]:
y.shape

(100, 1)

In [9]:
X

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 1],
       [1, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 0, 0],
       [1, 1, 1, 1],
       [0, 1, 1, 1],
       [0, 1, 1, 1],
       [1, 1, 0, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 1, 1, 1],
       [0, 1, 0, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 0, 0, 0],
       [0, 0, 1, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 1, 0, 1],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 0, 0, 0],
       [1, 0,

P(y=1/x_test) = P(x_test/y=1). P(y=1)/P(x_test)

P(y=1/x_test)>P(y=0/x_test) ~ 1 else 0 

P(x_test/y=1) = MLE for y== 1 for every feature

In [17]:
P1 = y[y==1].shape[0]/y.shape[0]

In [14]:
P1

0.5

In [15]:
P0 = y[y==0].shape[0]/y.shape[0]

In [16]:
P0

0.5

P(f=1|y=1) = no of rows in f=1 column which has target y == 1 / y[y==1].shape[0]

In [36]:
y.shape

(100, 1)

In [39]:
ind = y==1

In [48]:
pf0y1 = X[(y.ravel()==1) & (X[:,0] == 1) ].shape[0]/y[y==1].shape[0]

In [57]:
X.shape

(100, 4)

In [85]:
Y_train.shape

(70, 1)

In [49]:
pf0y1

0.26

In [147]:
Y_train[Y_train==1].shape

(350,)

In [143]:
feature1_y0 = np.zeros(X_train.shape[1])
feature1_y1 = np.zeros(X_train.shape[1])
for i in range(X_train.shape[1]):
    pfi1y1 = (X_train[(Y_train.ravel()==1) & (X_train[:,i] == 1) ].shape[0] + 1)/(Y_train[Y_train==1].shape[0]+2)
    feature1_y1[i] = pfi1y1
    pfi1y0 = (X_train[(Y_train.ravel()==0) & (X_train[:,i] == 1) ].shape[0] + 1)/(Y_train[Y_train==0].shape[0]+2)
    feature1_y0[i] = pfi1y0
    

In [211]:
f1y0 = feature1_y0

In [212]:
f1y1 = feature1_y1

In [89]:
test = X[0]

In [90]:
p_0 = P1
p_1 =P0
for i in range(X.shape[1]):
    if test[i] == 0:
        p_0 *= 1-feature1_y0[i]
        p_1 *= 1-feature1_y1[i]
    else:
        p_0 *= feature1_y0[i]
        p_1 *= feature1_y1[i]
print(p_0,p_1)
    

0.0041746585159833345 0.21609997023913732


In [91]:
y[0]

array([1])

Binaries features

In [73]:
l = np.array([23,25,45,89,93,33])
median = np.median(l,axis=0)
l_bin = (l >=median).astype(int)

In [74]:
l_bin

array([0, 0, 1, 1, 1, 0])

In [340]:
class Bernoulli_naive_bayes:
    def __init__(self,alpha=1,Binarize=False,fit_prior=True,threshold=0):
        self.bindata = Binarize
        self.threshold = threshold
        self.fit_prior = fit_prior
        self.lapace_const = alpha
        
    def compute_bayes(self,X,y):
        self.feature1_y0 = np.zeros(X.shape[1])
        self.feature1_y1 = np.zeros(X.shape[1])
        for i in range(X.shape[1]):
            pfi1y1 = (X[(y.ravel()==1) & (X[:,i] == 1) ].shape[0] + self.lapace_const)/(y[y==1].shape[0]+(2*self.lapace_const))
            self.feature1_y1[i] = pfi1y1
            pfi1y0 = (X[(y.ravel() == 0) & (X[:,i] == 1)].shape[0]+self.lapace_const)/(y[y==0].shape[0]+(2*self.lapace_const))
            self.feature1_y0[i] = pfi1y0
            
            
    def fit(self,X,y):
        if self.bindata ==True:
            
            X_bin = (X >self.threshold).astype(int)
            self.features = X_bin 
        else:
            self.features = X 
        self.target = y
        self.prior = y[y==1].shape[0]/y.shape[0]
        self.compute_bayes(self.features,self.target)
        
    def predict_point(self,x):
        p_0 = 0
        p_1 =0
        if self.fit_prior == True:
            p_1 = np.log(self.prior)
            p_0 = np.log(1-self.prior)
        for i in range(len(x)):
            if  x[i] == 0:
                p_0 += np.log(1-self.feature1_y0[i])
                p_1 += np.log(1-self.feature1_y1[i])
            else:
                p_0 += np.log(self.feature1_y0[i])
                p_1 += np.log(self.feature1_y1[i])
       
        if p_0>p_1:
            return 0
        return 1
            
    def predict(self,X):
        if self.bindata == True:
            X = (X >self.threshold).astype(int)
        preds = np.zeros(X.shape[0])
        
        for i in range(X.shape[0]):
            prediction = self.predict_point(X[i])
            preds[i] = prediction
            
        
        return preds 
            
            
        
        
            

In [320]:
from sklearn.datasets import make_classification
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [321]:
X, y = make_classification(n_samples=1000, n_features=10, 
                           n_informative=5, n_redundant=0, 
                           n_classes=2, random_state=42)

In [322]:
from sklearn.preprocessing import Binarizer

In [292]:
bini = Binarizer()
X_bin = bini.fit_transform(X)

In [246]:
X_bin[3]

array([0., 1., 1., 0., 1., 0., 1., 1., 1., 1.])

In [266]:
X_bin2 = (X >=0).astype(int)

In [268]:
np.sum(X_bin != X_bin2)

0

In [323]:
X

array([[ 3.86239664, -0.53555708, -0.01563761, ..., -0.33032079,
         3.25494185,  1.42375408],
       [-2.75566887,  0.81133032, -3.80487368, ..., -2.12421181,
        -1.9777969 ,  0.55165227],
       [ 1.37952235,  0.86515655,  2.43884712, ...,  1.18589537,
         0.81238553,  1.29054823],
       ...,
       [ 1.33017686,  0.08528407,  2.77181538, ..., -1.33552426,
         0.72486005,  1.73966525],
       [-1.19160029,  0.37709022,  1.58535027, ..., -2.02342646,
        -0.02961941, -1.07821817],
       [ 1.46458697,  0.39844805,  2.07032359, ...,  0.59166715,
         0.43877996,  0.30288328]])

In [344]:
bn = Bernoulli_naive_bayes(Binarize=True,fit_prior=True)

In [345]:
X.shape

(1000, 10)

In [346]:
X_train,X_test = X[:700],X[700:]
Y_train,Y_test = y[:700],y[700:]

In [347]:
bn.fit(X_train,Y_train)

In [348]:
print(classification_report(Y_train,bn.predict(X_train)))

              precision    recall  f1-score   support

           0       0.71      0.77      0.74       350
           1       0.75      0.69      0.72       350

    accuracy                           0.73       700
   macro avg       0.73      0.73      0.73       700
weighted avg       0.73      0.73      0.73       700



In [349]:
print(classification_report(Y_test,bn.predict(X_test)))

              precision    recall  f1-score   support

           0       0.66      0.74      0.70       151
           1       0.70      0.62      0.65       149

    accuracy                           0.68       300
   macro avg       0.68      0.68      0.68       300
weighted avg       0.68      0.68      0.68       300



lets compare with Scikit-learn

In [330]:
from sklearn.naive_bayes import BernoulliNB

In [332]:
nb = BernoulliNB(binarize=True,fit_prior=True)

In [333]:
nb.fit(X_train,Y_train)

BernoulliNB(binarize=True)

In [334]:
print(classification_report(Y_train,nb.predict(X_train)))

              precision    recall  f1-score   support

           0       0.69      0.67      0.68       350
           1       0.68      0.69      0.69       350

    accuracy                           0.68       700
   macro avg       0.68      0.68      0.68       700
weighted avg       0.68      0.68      0.68       700



In [335]:
print(classification_report(Y_test,nb.predict(X_test)))

              precision    recall  f1-score   support

           0       0.71      0.62      0.66       151
           1       0.66      0.74      0.70       149

    accuracy                           0.68       300
   macro avg       0.68      0.68      0.68       300
weighted avg       0.68      0.68      0.68       300



In [341]:
bn2 = Bernoulli_naive_bayes(Binarize=True,fit_prior=True,threshold=2)

In [342]:
bn2.fit(X_train,Y_train)

In [343]:
print(classification_report(Y_train,bn2.predict(X_train)))

              precision    recall  f1-score   support

           0       0.76      0.39      0.52       350
           1       0.59      0.88      0.71       350

    accuracy                           0.63       700
   macro avg       0.68      0.63      0.61       700
weighted avg       0.68      0.63      0.61       700

